
# Term color
export TERM=xterm-256color

# Aliases
if [ -f $HOME/.bash_aliases ]; then
	 . $HOME/.bash_aliases
fi

if [ -f /etc/bash_completion ]; then
	 . /etc/bash_completion
fi

alias ls='ls --color'
export M2_HOME="$HOME/Opt/maven3"
export PATH="$PATH:$HOME/bin:$HOME/Bin:$HOME/Opt/maven3/bin"
export PS1="\[\033[1;37m\]-(\[\033[1;31m\]\w\[\033[1;37m\])-\n(\[\033[1;32m\]\u\[\033[1;31m\]@\[\033[1;36m\]\h\[\033[1;37m\])-$ "

